name: Java CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/*.jar
        
  customaction:
    runs-on: ubuntu-latest
    steps:
    - uses: nvaishnav/custom-actions/echo-message-action@main

  echomessage:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Printing message from main workflow"
      shell: bash

  currentDay:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/print-current-day
    
  
